# Hexo配置
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 呓语の小屋
subtitle: ''
description: '让理想生活的样子清晰可见'
keywords: Hexo,呓语の小屋,呓语的小屋,个人博客,是zzy呀,前端
author: 是zzy呀
language: zh-CN
timezone: ''

# URL
## 在此处设置网站url。例如，如果您使用GitHub页面，请将url设置为'https://username.github.io/project'
url: https://blog.zhaozeyu.top
permalink: :hash/
permalink_defaults:
pretty_urls:
  trailing_index: false # 设置为false以从永久链接中删除尾随的“index.html”
  trailing_html: true # 设置为false以从永久链接中删除尾随的“.html”

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 写作
new_post_name: :title.md # 新文章的文件名称
default_layout: post
titlecase: false # 把标题转换为 title case
external_link:
  enable: true # 在新标签中打开链接
  field: site # 对整个网站（site）生效或仅对文章（post）生效
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# 主页设置
# path: 博客索引页的根路径。（默认值=“”）
# per_page：每页显示的帖子。（0=禁用分页）
# order_by：发布订单。（默认情况下按日期降序排列）
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类 & 标签
default_category: uncategorized
category_map:
tag_map:

# 元数据元素
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期/时间格式
## Hexo使用Moment.js解析和显示日期
## 您可以自定义中定义的日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option支持'mtime'、'date'、'empty'
updated_option: 'mtime'

# 标页码
## 将per_page设置为0以禁用分页
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: 选项仅适用于“source/”文件夹
include:
exclude:
ignore:

# 扩展
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# 部署
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type:
  repo:
  branch:

# 插件
plugins:
  - hexo-algoliasearch

# 搜索引擎
algolia:
  appId: "JGXVE8KFC5"
  apiKey: "49c12c4ec61a3b5d6d33d991a4fb5ce9"
  adminApiKey: "5d696331954c819f63e32282384138a5"
  chunkSize: 5000
  indexName: "my-hexo-blog"
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title

# 音乐
aplayer:
  meting: true
  asset_inject: false

# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # 开关
  priority: 5 #过滤器优先权
  issues: false #issues标签依赖注入开关
  link:
    placeholder: /img/link.png #link_card标签默认的图标图片
  CDN:
    anima: https://cdn.staticfile.org/animate.css/4.1.1/animate.min.css #动画标签anima的依赖
    jquery: https://cdn.staticfile.org/jquery/3.6.4/jquery.min.js #issues标签依赖
    issues: https://npm.elemecdn.com/blogassets@1.1.4/hexo-butterfly-tag-plugins-plus/issues.js #issues标签依赖
    iconfont: //at.alicdn.com/t/c/font_3965311_w030kg821p.js #参看 https://akilar.top/posts/d2ebecef/
    carousel: https://npm.elemecdn.com/blogassets@1.1.4/hexo-butterfly-tag-plugins-plus/carousel-touch.js
    tag_plugins_css: https://npm.elemecdn.com/blogassets@1.1.4/hexo-butterfly-tag-plugins-plus/tag_plugins.css

# 豆瓣爬取
douban:
  id: 246556043
  builtin: true
  item_per_page: 10
  meta_max_line: 4
  movie:
    path: fun/movies/index.html
    title: '电影'
    quote: '数据来源于豆瓣电影官网'
    option:
      aside: false
  timeout: 10000