name: 自动部署

# 当有新的改动推送到 main 分支时，执行 Action
on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 校验分支
        uses: actions/checkout@v3
        with:
          # 要校验的分支
          ref: main
          # 要获取的提交数。0表示所有分支和标记的所有历史记录。默认值：1
          fetch-depth: 0

      - name: 同步本地文件时间戳
        run: |
          git ls-files -z | while read -d '' path; do touch -d $(git log -1 --format="@%ct" "$path") "$path"; done

      - name: 安装node环境
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: 安装Hexo环境
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g

      - name: 缓存Hexo文件
        id: cache-npm
        uses: actions/checkout@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: 安装依赖
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: 生成静态文件
        run: |
          hexo clean
          hexo generate
          hexo algolia

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public

      # - name: 部署到服务器
      #   uses: easingthemes/ssh-deploy@main
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ARGS: "-rltgoDzvO --delete"
      #     SOURCE: "./public/*"
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.REMOTE_TARGET }}
